# Make sure you set DOCKER_HOST_IP environment variable

version: '3.7'

services:
  engine:
    container_name: epi-engine
    image: epi-engine:latest
    build:
      context: ../engine
    depends_on:
      - kafka
    environment:
      RUST_LOG: INFO
      EPI_KAFKA_URL: "kafka:29092"
    command: cargo run --release -- --daemon

  server:
    image: epi-web:latest
    container_name: epi-server
    build:
     context: ../web
    environment:
      DATABASE_URL: "mongodb://db:27017"
    working_dir: /web/server    
    command: npm start
    depends_on:
      - mongodb_container
    ports:
      - "3000:3000"

  kafka-consumer:
    image: epi-web:latest
    container_name: epi-kafka-consumers
    environment:
      DATABASE_URL: "mongodb://db:27017"
    build:
      context: ../web
    working_dir: /web/server  
    command: npm run start-consumers  
    depends_on:
      - kafka

  react-spa:
    image: epi-web:latest
    container_name: epi-react-spa
    build:
     context: ../web
    working_dir: /web/react-spa 
    command: sh -c "npm rebuild node-sass && npm start"
    depends_on:
      - server
    ports:
      - "3001:3001"
    

